# Generated by Django 5.1.5 on 2026-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_rename_issue_feedback_message_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default=5, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
