# Generated by Django 5.1.5 on 2026-03-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_feedback_rating_feedback_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='issue',
            new_name='message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
